name: Build and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      # Use GitHub Actions' cache to shorten build times and decrease load on servers.
      - uses: actions/setup-ruby@v1
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install
      
      - uses: helaili/jekyll-action@2.0.4
        env:
          # Ideally use GITHUB_TOKEN but it gives error for this action.
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}